# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe2c775c1be83dc6a57ea367bc8e91164c1f91a5d4159d6855a8c4ec276af03c8e4f6a5967718795d83f57640df74e5b604f7b4b9f625a84fef7887ed1fd4f3e

test:
  secret_key_base: b0b2d4885b32fa25ed5ca6562cf1e1e35f6953538512d8afcc8657ec408ce4923a7ba333bc40405262e9ee73a06f95d417ee9c2724537491b00a8b9cc535a039

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
